### ISSUE TITLE
Some server issue

### ISSUE THREAD

**Issue by tadatuta** [enb-make/enb#410]
After upgrade to `enb^1.0.1` (https://github.com/bem/project-stub/commit/7b3b66f4a36819bf90c782fc8fcfa2ee5de790c5) there are a few `build failed` logs in console on each page refresh in `project-stub` (still everything works fine and no such logs appear on `enb make`).

**Comment by blond** [comment]
This is due to the fact that server is trying to build images. 

These images are not ENB targets. Therefore, each such assembly fails with `TargetNotFoundError` and ENB logs `build failed` to console.

I think we need to add the `strict` option to make command. If `strict: true` then as now assembly will fails with `TargetNotFoundError`. If `strict: false` then ENB will ignore such targets. By default — `strict: true`.

**Comment by blond** [comment]
And ENB server should use `strict: false` always.
